<!-- AWP_In_Variable Name='"DATA_TRANSFER".SPEED_ACTUAL' -->
<!-- AWP_In_Variable Name='"DATA_TRANSFER".FREQUENCY_ACTUAL' -->
<!-- AWP_In_Variable Name='"DATA_TRANSFER".VOLTAGE_ACTUAL' -->
<!-- AWP_In_Variable Name='"DATA_TRANSFER".CURRENT_ACTUAL' -->
<!-- AWP_In_Variable Name='"DATA_TRANSFER".TORQUE_ACTUAL' -->
<!-- AWP_In_Variable Name='"DATA_TRANSFER".TEMPERATURE_ACTUAL' -->
{"speed"::="DATA_TRANSFER".SPEED_ACTUAL:,"frequency"::=DATA_TRANSFER".FREQUENCY_ACTUAL:,"voltage"::=DATA_TRANSFER".VOLTAGE_ACTUAL:,"current"::=DATA_TRANSFER".CURRENT_ACTUAL:,"torque"::=DATA_TRANSFER".TORQUE_ACTUAL:,"temperature"::=DATA_TRANSFER".TEMPERATURE_ACTUAL:}